### ISSUE TITLE
Change or remove meta descriptions on pages

### ISSUE THREAD

**Issue by stropitek** [cheminfo/cheminfo.github.io#18]
Currently the value of the meta description is not configured on any page, which affects what is seen in search engines results and when sharing links on social networks.

Example when sharing on Discord:
![image](https://user-images.githubusercontent.com/4118690/114674290-5d43fa00-9d07-11eb-93e1-bae0ea8d5901.png)

The text below the link depends  on the page's title and on the `description` meta tag

```html
<meta name="description" content="Insert meta description here">
```

**Comment by kjappelbaum** [comment]
yes, thanks I didn't have time to work on it last night but will take care.
